module.exports = {
  aboutSidebarHtml: '',
  bannerImageName: 'images_course_image.jpg',
  bannerImageAssetPath:
    '/asset-v1:edX+M12+2T2023+type@asset+block@images_courseasdd_image.jpg',
  certificateAvailableDate: null,
  certificatesDisplayBehavior: 'end',
  courseId: 'M12',
  courseImageAssetPath: '/static/studio/images/pencils.jpg',
  courseImageName: '',
  description: 'description',
  duration: '10h',
  effort: '10h',
  endDate: null,
  enrollmentEnd: null,
  enrollmentStart: null,
  entranceExamEnabled: 'true',
  entranceExamId: '',
  entranceExamMinimumScorePct: '50',
  instructorInfo: {
    instructors: [
      {
        name: 'foo bar',
        title: 'title',
        organization: 'org',
        image: 'image',
        bio: 'biography',
      },
    ],
  },
  introVideo: null,
  language: 'creative-commons: ver=4.0 BY NC ND',
  learningInfo: ['foo'],
  license: 'creative-commons: ver=4.0 BY NC ND',
  org: 'edX',
  overview: "<section class='about'></section>",
  preRequisiteCourses: [],
  run: '2T2023',
  selfPaced: false,
  shortDescription: '',
  startDate: '2023-06-14T00:00:00Z',
  subtitle: 'subtitle',
  syllabus: null,
  title: 'title',
  videoThumbnailImageAssetPath:
    '/asset-v1:edX+M12+2T2023+type@asset+block@images_course_image.jpg',
  videoThumbnailImageName: 'images_course_image.jpg',
};
