import { TagData, TagTreeNode } from './tagTree';

export const rawData: TagData[] = [
  {
    value: 'ab',
    externalId: null,
    childCount: 2,
    descendantCount: 4,
    depth: 0,
    parentValue: null,
    id: 31,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=ab&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'aaa',
    externalId: null,
    childCount: 1,
    descendantCount: 1,
    depth: 1,
    parentValue: 'ab',
    id: 49,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=aaa&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'aa',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'aaa',
    id: 52,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'ab2',
    externalId: null,
    childCount: 1,
    descendantCount: 1,
    depth: 1,
    parentValue: 'ab',
    id: 50,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=ab2&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'S3',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'ab2',
    id: 51,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Brass2',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 36,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Celli',
    externalId: null,
    childCount: 1,
    descendantCount: 2,
    depth: 0,
    parentValue: null,
    id: 34,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Celli&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'ViolaDaGamba',
    externalId: null,
    childCount: 1,
    descendantCount: 1,
    depth: 1,
    parentValue: 'Celli',
    id: 42,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=ViolaDaGamba&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Soprano',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'ViolaDaGamba',
    id: 46,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Contrabass',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 35,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Electrodrum',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 38,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Electronic instruments',
    externalId: 'ELECTRIC',
    childCount: 2,
    descendantCount: 2,
    depth: 0,
    parentValue: null,
    id: 3,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Electronic+instruments&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Synthesizer',
    externalId: 'SYNTH',
    childCount: 0,
    descendantCount: 0,
    depth: 1,
    parentValue: 'Electronic instruments',
    id: 25,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Theramin',
    externalId: 'THERAMIN',
    childCount: 0,
    descendantCount: 0,
    depth: 1,
    parentValue: 'Electronic instruments',
    id: 9,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Fiddle',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 54,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'grand piano',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 48,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Horns',
    externalId: null,
    childCount: 1,
    descendantCount: 2,
    depth: 0,
    parentValue: null,
    id: 55,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Horns&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'English Horn',
    externalId: null,
    childCount: 1,
    descendantCount: 1,
    depth: 1,
    parentValue: 'Horns',
    id: 56,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=English+Horn&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Small English Horn',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'English Horn',
    id: 57,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Keyboard',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 37,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Kid drum',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 33,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Mezzosopranocello',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 41,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Oriental',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 53,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Percussion instruments',
    externalId: 'PERCUSS',
    childCount: 4,
    descendantCount: 11,
    depth: 0,
    parentValue: null,
    id: 2,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Percussion+instruments&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Chordophone',
    externalId: 'CHORD',
    childCount: 1,
    descendantCount: 1,
    depth: 1,
    parentValue: 'Percussion instruments',
    id: 10,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Chordophone&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Piano',
    externalId: 'PIANO',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Chordophone',
    id: 29,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Drum',
    externalId: null,
    childCount: 1,
    descendantCount: 1,
    depth: 1,
    parentValue: 'Percussion instruments',
    id: 45,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Drum&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'bass drum',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Drum',
    id: 47,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Idiophone',
    externalId: 'BELLS',
    childCount: 2,
    descendantCount: 2,
    depth: 1,
    parentValue: 'Percussion instruments',
    id: 5,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Idiophone&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Celesta',
    externalId: 'CELESTA',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Idiophone',
    id: 26,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Hi-hat',
    externalId: 'HI-HAT',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Idiophone',
    id: 27,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Membranophone',
    externalId: 'DRUMS',
    childCount: 2,
    descendantCount: 3,
    depth: 1,
    parentValue: 'Percussion instruments',
    id: 6,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Membranophone&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Cajón',
    externalId: 'CAJÓN',
    childCount: 1,
    descendantCount: 1,
    depth: 2,
    parentValue: 'Membranophone',
    id: 7,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Caj%C3%B3n&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Tabla',
    externalId: 'TABLA',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Membranophone',
    id: 28,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Recorder',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 39,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'String instruments',
    externalId: 'STRINGS',
    childCount: 3,
    descendantCount: 9,
    depth: 0,
    parentValue: null,
    id: 4,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=String+instruments&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Bowed strings',
    externalId: 'BOW',
    childCount: 3,
    descendantCount: 3,
    depth: 1,
    parentValue: 'String instruments',
    id: 18,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Bowed+strings&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Cello',
    externalId: 'CELLO',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Bowed strings',
    id: 20,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Viola',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Bowed strings',
    id: 44,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Violin',
    externalId: 'VIOLIN',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Bowed strings',
    id: 19,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Other strings',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 1,
    parentValue: 'String instruments',
    id: 43,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Plucked strings',
    externalId: 'PLUCK',
    childCount: 3,
    descendantCount: 3,
    depth: 1,
    parentValue: 'String instruments',
    id: 14,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Plucked+strings&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Banjo',
    externalId: 'BANJO',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Plucked strings',
    id: 17,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Harp',
    externalId: 'HARP',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Plucked strings',
    id: 16,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Mandolin',
    externalId: 'MANDOLIN',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Plucked strings',
    id: 15,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Subbass',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 40,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Trumpets',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 30,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Wind instruments',
    externalId: 'WINDS',
    childCount: 2,
    descendantCount: 7,
    depth: 0,
    parentValue: null,
    id: 1,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Wind+instruments&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Brass',
    externalId: 'BRASS',
    childCount: 2,
    descendantCount: 2,
    depth: 1,
    parentValue: 'Wind instruments',
    id: 11,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Brass&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Trumpet',
    externalId: 'TRUMPET',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Brass',
    id: 23,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Tuba',
    externalId: 'TUBA',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Brass',
    id: 24,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Woodwinds',
    externalId: 'WOODS',
    childCount: 3,
    descendantCount: 3,
    depth: 1,
    parentValue: 'Wind instruments',
    id: 12,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Woodwinds&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Clarinet',
    externalId: 'CLARINET',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Woodwinds',
    id: 21,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Flute',
    externalId: 'FLUTE',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Woodwinds',
    id: 13,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Oboe',
    externalId: 'OBOE',
    childCount: 0,
    descendantCount: 0,
    depth: 2,
    parentValue: 'Woodwinds',
    id: 22,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Xyllophones',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 32,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
];

export const treeRowData: TagTreeNode[] = [
  {
    value: 'ab',
    externalId: null,
    childCount: 2,
    descendantCount: 4,
    depth: 0,
    parentValue: null,
    id: 31,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=ab&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
    subRows: [
      {
        value: 'aaa',
        externalId: null,
        childCount: 1,
        descendantCount: 1,
        depth: 1,
        parentValue: 'ab',
        id: 49,
        subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=aaa&full_depth_threshold=1000',
        canChangeTag: true,
        canDeleteTag: true,
        subRows: [
          {
            value: 'aa',
            externalId: null,
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'aaa',
            id: 52,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
        ],
      },
      {
        value: 'ab2',
        externalId: null,
        childCount: 1,
        descendantCount: 1,
        depth: 1,
        parentValue: 'ab',
        id: 50,
        subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=ab2&full_depth_threshold=1000',
        canChangeTag: true,
        canDeleteTag: true,
        subRows: [
          {
            value: 'S3',
            externalId: null,
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'ab2',
            id: 51,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
        ],
      },
    ],
  },
  {
    value: 'Brass2',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 36,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Celli',
    externalId: null,
    childCount: 1,
    descendantCount: 2,
    depth: 0,
    parentValue: null,
    id: 34,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Celli&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
    subRows: [
      {
        value: 'ViolaDaGamba',
        externalId: null,
        childCount: 1,
        descendantCount: 1,
        depth: 1,
        parentValue: 'Celli',
        id: 42,
        subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=ViolaDaGamba&full_depth_threshold=1000',
        canChangeTag: true,
        canDeleteTag: true,
        subRows: [
          {
            value: 'Soprano',
            externalId: null,
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'ViolaDaGamba',
            id: 46,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
        ],
      },
    ],
  },
  {
    value: 'Contrabass',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 35,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Electrodrum',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 38,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Electronic instruments',
    externalId: 'ELECTRIC',
    childCount: 2,
    descendantCount: 2,
    depth: 0,
    parentValue: null,
    id: 3,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Electronic+instruments&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
    subRows: [
      {
        value: 'Synthesizer',
        externalId: 'SYNTH',
        childCount: 0,
        descendantCount: 0,
        depth: 1,
        parentValue: 'Electronic instruments',
        id: 25,
        subTagsUrl: null,
        canChangeTag: true,
        canDeleteTag: true,
      },
      {
        value: 'Theramin',
        externalId: 'THERAMIN',
        childCount: 0,
        descendantCount: 0,
        depth: 1,
        parentValue: 'Electronic instruments',
        id: 9,
        subTagsUrl: null,
        canChangeTag: true,
        canDeleteTag: true,
      },
    ],
  },
  {
    value: 'Fiddle',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 54,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'grand piano',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 48,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Horns',
    externalId: null,
    childCount: 1,
    descendantCount: 2,
    depth: 0,
    parentValue: null,
    id: 55,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Horns&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
    subRows: [
      {
        value: 'English Horn',
        externalId: null,
        childCount: 1,
        descendantCount: 1,
        depth: 1,
        parentValue: 'Horns',
        id: 56,
        subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=English+Horn&full_depth_threshold=1000',
        canChangeTag: true,
        canDeleteTag: true,
        subRows: [
          {
            value: 'Small English Horn',
            externalId: null,
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'English Horn',
            id: 57,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
        ],
      },
    ],
  },
  {
    value: 'Keyboard',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 37,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Kid drum',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 33,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Mezzosopranocello',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 41,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Oriental',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 53,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Percussion instruments',
    externalId: 'PERCUSS',
    childCount: 4,
    descendantCount: 11,
    depth: 0,
    parentValue: null,
    id: 2,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Percussion+instruments&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
    subRows: [
      {
        value: 'Chordophone',
        externalId: 'CHORD',
        childCount: 1,
        descendantCount: 1,
        depth: 1,
        parentValue: 'Percussion instruments',
        id: 10,
        subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Chordophone&full_depth_threshold=1000',
        canChangeTag: true,
        canDeleteTag: true,
        subRows: [
          {
            value: 'Piano',
            externalId: 'PIANO',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Chordophone',
            id: 29,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
        ],
      },
      {
        value: 'Drum',
        externalId: null,
        childCount: 1,
        descendantCount: 1,
        depth: 1,
        parentValue: 'Percussion instruments',
        id: 45,
        subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Drum&full_depth_threshold=1000',
        canChangeTag: true,
        canDeleteTag: true,
        subRows: [
          {
            value: 'bass drum',
            externalId: null,
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Drum',
            id: 47,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
        ],
      },
      {
        value: 'Idiophone',
        externalId: 'BELLS',
        childCount: 2,
        descendantCount: 2,
        depth: 1,
        parentValue: 'Percussion instruments',
        id: 5,
        subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Idiophone&full_depth_threshold=1000',
        canChangeTag: true,
        canDeleteTag: true,
        subRows: [
          {
            value: 'Celesta',
            externalId: 'CELESTA',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Idiophone',
            id: 26,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
          {
            value: 'Hi-hat',
            externalId: 'HI-HAT',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Idiophone',
            id: 27,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
        ],
      },
      {
        value: 'Membranophone',
        externalId: 'DRUMS',
        childCount: 2,
        descendantCount: 3,
        depth: 1,
        parentValue: 'Percussion instruments',
        id: 6,
        subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Membranophone&full_depth_threshold=1000',
        canChangeTag: true,
        canDeleteTag: true,
        subRows: [
          {
            value: 'Cajón',
            externalId: 'CAJÓN',
            childCount: 1,
            descendantCount: 1,
            depth: 2,
            parentValue: 'Membranophone',
            id: 7,
            subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Caj%C3%B3n&full_depth_threshold=1000',
            canChangeTag: true,
            canDeleteTag: true,
          },
          {
            value: 'Tabla',
            externalId: 'TABLA',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Membranophone',
            id: 28,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
        ],
      },
    ],
  },
  {
    value: 'Recorder',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 39,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'String instruments',
    externalId: 'STRINGS',
    childCount: 3,
    descendantCount: 9,
    depth: 0,
    parentValue: null,
    id: 4,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=String+instruments&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
    subRows: [
      {
        value: 'Bowed strings',
        externalId: 'BOW',
        childCount: 3,
        descendantCount: 3,
        depth: 1,
        parentValue: 'String instruments',
        id: 18,
        subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Bowed+strings&full_depth_threshold=1000',
        canChangeTag: true,
        canDeleteTag: true,
        subRows: [
          {
            value: 'Cello',
            externalId: 'CELLO',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Bowed strings',
            id: 20,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
          {
            value: 'Viola',
            externalId: null,
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Bowed strings',
            id: 44,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
          {
            value: 'Violin',
            externalId: 'VIOLIN',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Bowed strings',
            id: 19,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
        ],
      },
      {
        value: 'Other strings',
        externalId: null,
        childCount: 0,
        descendantCount: 0,
        depth: 1,
        parentValue: 'String instruments',
        id: 43,
        subTagsUrl: null,
        canChangeTag: true,
        canDeleteTag: true,
      },
      {
        value: 'Plucked strings',
        externalId: 'PLUCK',
        childCount: 3,
        descendantCount: 3,
        depth: 1,
        parentValue: 'String instruments',
        id: 14,
        subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Plucked+strings&full_depth_threshold=1000',
        canChangeTag: true,
        canDeleteTag: true,
        subRows: [
          {
            value: 'Banjo',
            externalId: 'BANJO',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Plucked strings',
            id: 17,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
          {
            value: 'Harp',
            externalId: 'HARP',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Plucked strings',
            id: 16,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
          {
            value: 'Mandolin',
            externalId: 'MANDOLIN',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Plucked strings',
            id: 15,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
        ],
      },
    ],
  },
  {
    value: 'Subbass',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 40,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Trumpets',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 30,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
  {
    value: 'Wind instruments',
    externalId: 'WINDS',
    childCount: 2,
    descendantCount: 7,
    depth: 0,
    parentValue: null,
    id: 1,
    subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Wind+instruments&full_depth_threshold=1000',
    canChangeTag: true,
    canDeleteTag: true,
    subRows: [
      {
        value: 'Brass',
        externalId: 'BRASS',
        childCount: 2,
        descendantCount: 2,
        depth: 1,
        parentValue: 'Wind instruments',
        id: 11,
        subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Brass&full_depth_threshold=1000',
        canChangeTag: true,
        canDeleteTag: true,
        subRows: [
          {
            value: 'Trumpet',
            externalId: 'TRUMPET',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Brass',
            id: 23,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
          {
            value: 'Tuba',
            externalId: 'TUBA',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Brass',
            id: 24,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
        ],
      },
      {
        value: 'Woodwinds',
        externalId: 'WOODS',
        childCount: 3,
        descendantCount: 3,
        depth: 1,
        parentValue: 'Wind instruments',
        id: 12,
        subTagsUrl: 'http://studio.local.openedx.io:8001/api/content_tagging/v1/taxonomies/1/tags/?parent_tag=Woodwinds&full_depth_threshold=1000',
        canChangeTag: true,
        canDeleteTag: true,
        subRows: [
          {
            value: 'Clarinet',
            externalId: 'CLARINET',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Woodwinds',
            id: 21,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
          {
            value: 'Flute',
            externalId: 'FLUTE',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Woodwinds',
            id: 13,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
          {
            value: 'Oboe',
            externalId: 'OBOE',
            childCount: 0,
            descendantCount: 0,
            depth: 2,
            parentValue: 'Woodwinds',
            id: 22,
            subTagsUrl: null,
            canChangeTag: true,
            canDeleteTag: true,
          },
        ],
      },
    ],
  },
  {
    value: 'Xyllophones',
    externalId: null,
    childCount: 0,
    descendantCount: 0,
    depth: 0,
    parentValue: null,
    id: 32,
    subTagsUrl: null,
    canChangeTag: true,
    canDeleteTag: true,
  },
];
