module.exports = {
  language_code: 'en',
  action: 'view',
  xblock: {
    display_name: 'Getting Started',
    display_type: 'Unit',
    category: 'vertical',
  },
  is_unit_page: true,
  is_collapsible: false,
  position: 1,
  prev_url: '%2Fcontainer%2Fblock-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40vertical%2Bblock%40vertical_0270f6de40fc',
  next_url: '%2Fcontainer%2Fblock-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40vertical%2Bblock%404f6c1b4e316a419ab5b6bf30e6c708e9',
  new_unit_category: 'vertical',
  outline_url: '/course/course-v1:edX+DemoX+Demo_Course?format=concise',
  ancestor_xblocks: [
    {
      children: [
        {
          url: '/course/course-v1:edX+DemoX+Demo_Course?show=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40chapter%2Bblock%40d8a6192ade314473a78242dfeedfbf5b',
          display_name: 'Introduction 2',
        },
        {
          url: '/course/course-v1:edX+DemoX+Demo_Course?show=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40chapter%2Bblock%40interactive_demonstrations',
          display_name: 'Example Week 1: Getting Started',
        },
        {
          url: '/course/course-v1:edX+DemoX+Demo_Course?show=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40chapter%2Bblock%40graded_interactions',
          display_name: 'Example Week 2: Get Interactive',
        },
        {
          url: '/course/course-v1:edX+DemoX+Demo_Course?show=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40chapter%2Bblock%40social_integration',
          display_name: 'Example Week 3: Be Social',
        },
        {
          url: '/course/course-v1:edX+DemoX+Demo_Course?show=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40chapter%2Bblock%401414ffd5143b4b508f739b563ab468b7',
          display_name: 'About Exams and Certificates',
        },
      ],
      title: 'Example Week 1: Getting Started',
      is_last: false,
    },
    {
      children: [
        {
          url: '/course/course-v1:edX+DemoX+Demo_Course?show=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40sequential%2Bblock%4019a30717eff543078a5d94ae9d6c18a5',
          display_name: 'Lesson 1 - Getting Started',
        },
        {
          url: '/course/course-v1:edX+DemoX+Demo_Course?show=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40sequential%2Bblock%40basic_questions',
          display_name: 'Homework - Question Styles',
        },
      ],
      title: 'Lesson 1 - Getting Started',
      is_last: true,
    },
  ],
  component_templates: [
    {
      type: 'advanced',
      templates: [
        {
          display_name: 'Annotation',
          category: 'annotatable',
          boilerplate_name: null,
          hinted: false,
          tab: 'common',
          support_level: true,
        },
        {
          display_name: 'Video',
          category: 'videoalpha',
          boilerplate_name: null,
          hinted: false,
          tab: 'common',
          support_level: true,
        },
      ],
      display_name: 'Advanced',
      support_legend: {
        show_legend: false,
        allow_unsupported_xblocks: false,
        documentation_label: 'Your Platform Name Here Support Levels:',
      },
    },
    {
      type: 'discussion',
      templates: [
        {
          display_name: 'Discussion',
          category: 'discussion',
          boilerplate_name: null,
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
      ],
      display_name: 'Discussion',
      support_legend: {
        show_legend: false,
        allow_unsupported_xblocks: false,
        documentation_label: 'Your Platform Name Here Support Levels:',
      },
    },
    {
      type: 'library',
      templates: [
        {
          display_name: 'Randomized Content Block',
          category: 'library_content',
          boilerplate_name: null,
          hinted: false,
          tab: 'common',
          support_level: true,
        },
      ],
      display_name: 'Library Content',
      support_legend: {
        show_legend: false,
        allow_unsupported_xblocks: false,
        documentation_label: 'Your Platform Name Here Support Levels:',
      },
    },
    {
      type: 'html',
      templates: [
        {
          display_name: 'Text',
          category: 'html',
          boilerplate_name: null,
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
        {
          display_name: 'Raw HTML',
          category: 'html',
          boilerplate_name: 'raw.yaml',
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
        {
          display_name: 'Zooming Image Tool',
          category: 'html',
          boilerplate_name: 'zooming_image.yaml',
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
        {
          display_name: 'IFrame Tool',
          category: 'html',
          boilerplate_name: 'iframe.yaml',
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
        {
          display_name: 'Anonymous User ID',
          category: 'html',
          boilerplate_name: 'anon_user_id.yaml',
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
        {
          display_name: 'Announcement',
          category: 'html',
          boilerplate_name: 'announcement.yaml',
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
      ],
      display_name: 'Text',
      support_legend: {
        show_legend: false,
        allow_unsupported_xblocks: false,
        documentation_label: 'Your Platform Name Here Support Levels:',
      },
    },
    {
      type: 'openassessment',
      templates: [
        {
          display_name: 'Peer Assessment Only',
          category: 'openassessment',
          boilerplate_name: 'peer-assessment',
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
        {
          display_name: 'Self Assessment Only',
          category: 'openassessment',
          boilerplate_name: 'self-assessment',
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
        {
          display_name: 'Staff Assessment Only',
          category: 'openassessment',
          boilerplate_name: 'staff-assessment',
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
        {
          display_name: 'Self Assessment to Peer Assessment',
          category: 'openassessment',
          boilerplate_name: 'self-to-peer',
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
        {
          display_name: 'Self Assessment to Staff Assessment',
          category: 'openassessment',
          boilerplate_name: 'self-to-staff',
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
      ],
      display_name: 'Open Response',
      support_legend: {
        show_legend: false,
        allow_unsupported_xblocks: false,
        documentation_label: 'Your Platform Name Here Support Levels:',
      },
    },
    {
      type: 'problem',
      templates: [
        {
          display_name: 'Blank Common Problem',
          category: 'problem',
          boilerplate_name: 'blank_common.yaml',
          hinted: false,
          tab: 'common',
          support_level: true,
        },
      ],
      display_name: 'Problem',
      support_legend: {
        show_legend: false,
        allow_unsupported_xblocks: false,
        documentation_label: 'Your Platform Name Here Support Levels:',
      },
    },
    {
      type: 'video',
      templates: [
        {
          display_name: 'Video',
          category: 'video',
          boilerplate_name: null,
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
      ],
      display_name: 'Video',
      support_legend: {
        show_legend: false,
        allow_unsupported_xblocks: false,
        documentation_label: 'Your Platform Name Here Support Levels:',
      },
    },
    {
      type: 'drag-and-drop-v2',
      templates: [
        {
          display_name: 'Drag and Drop',
          category: 'drag-and-drop-v2',
          boilerplate_name: null,
          hinted: false,
          tab: 'advanced',
          support_level: true,
        },
      ],
      display_name: 'Drag and Drop',
      support_legend: {
        show_legend: false,
        allow_unsupported_xblocks: false,
        documentation_label: 'Your Platform Name Here Support Levels:',
      },
    },
  ],
  xblock_info: {
    id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@867dddb6f55d410caaa9c1eb9c6743ec',
    display_name: 'Getting Started',
    category: 'vertical',
    has_children: true,
    edited_on: 'Jan 04, 2024 at 10:32 UTC',
    published: true,
    published_on: 'Dec 28, 2023 at 10:00 UTC',
    studio_url: '/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@867dddb6f55d410caaa9c1eb9c6743ec',
    released_to_students: true,
    release_date: 'Feb 05, 2013 at 05:00 UTC',
    visibility_state: 'needs_attention',
    has_explicit_staff_lock: false,
    start: '2013-02-05T05:00:00Z',
    graded: false,
    due_date: '',
    due: null,
    relative_weeks_due: null,
    format: null,
    course_graders: [
      'Homework',
      'Exam',
    ],
    has_changes: true,
    actions: {
      deletable: true,
      draggable: true,
      childAddable: true,
      duplicable: true,
    },
    explanatory_message: null,
    group_access: {},
    user_partitions: [
      {
        id: 50,
        name: 'Enrollment Track Groups',
        scheme: 'enrollment_track',
        groups: [
          {
            id: 2,
            name: 'Verified Certificate',
            selected: false,
            deleted: false,
          },
          {
            id: 1,
            name: 'Audit',
            selected: false,
            deleted: false,
          },
        ],
      },
    ],
    show_correctness: 'always',
    discussion_enabled: true,
    ancestor_info: {
      ancestors: [
        {
          id: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
          display_name: 'Lesson 1 - Getting Started',
          category: 'sequential',
          has_children: true,
          edited_on: 'Jan 04, 2024 at 10:32 UTC',
          published: true,
          published_on: 'Dec 28, 2023 at 10:00 UTC',
          studio_url: '/course/course-v1:edX+DemoX+Demo_Course?show=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40sequential%2Bblock%4019a30717eff543078a5d94ae9d6c18a5',
          released_to_students: true,
          release_date: 'Feb 05, 2013 at 05:00 UTC',
          visibility_state: 'needs_attention',
          has_explicit_staff_lock: false,
          start: '2013-02-05T05:00:00Z',
          graded: false,
          due_date: '',
          due: null,
          relative_weeks_due: null,
          format: null,
          course_graders: [
            'Homework',
            'Exam',
          ],
          has_changes: null,
          actions: {
            deletable: true,
            draggable: true,
            childAddable: true,
            duplicable: true,
          },
          explanatory_message: null,
          group_access: {},
          user_partitions: [
            {
              id: 50,
              name: 'Enrollment Track Groups',
              scheme: 'enrollment_track',
              groups: [
                {
                  id: 2,
                  name: 'Verified Certificate',
                  selected: false,
                  deleted: false,
                },
                {
                  id: 1,
                  name: 'Audit',
                  selected: false,
                  deleted: false,
                },
              ],
            },
          ],
          show_correctness: 'always',
          hide_after_due: false,
          is_proctored_exam: false,
          was_exam_ever_linked_with_external: false,
          online_proctoring_rules: '',
          is_practice_exam: false,
          is_onboarding_exam: false,
          is_time_limited: false,
          exam_review_rules: '',
          default_time_limit_minutes: null,
          proctoring_exam_configuration_link: null,
          supports_onboarding: false,
          show_review_rules: true,
          child_info: {
            category: 'vertical',
            display_name: 'Unit',
            children: [
              {
                id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@867dddb6f55d410caaa9c1eb9c6743ec',
                display_name: 'Getting Started',
                category: 'vertical',
                has_children: true,
                edited_on: 'Jan 04, 2024 at 10:32 UTC',
                published: true,
                published_on: 'Dec 28, 2023 at 10:00 UTC',
                studio_url: '/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@867dddb6f55d410caaa9c1eb9c6743ec',
                released_to_students: true,
                release_date: 'Feb 05, 2013 at 05:00 UTC',
                visibility_state: 'needs_attention',
                has_explicit_staff_lock: false,
                start: '2013-02-05T05:00:00Z',
                graded: false,
                due_date: '',
                due: null,
                relative_weeks_due: null,
                format: null,
                course_graders: [
                  'Homework',
                  'Exam',
                ],
                has_changes: true,
                actions: {
                  deletable: true,
                  draggable: true,
                  childAddable: true,
                  duplicable: true,
                },
                explanatory_message: null,
                group_access: {},
                user_partitions: [
                  {
                    id: 50,
                    name: 'Enrollment Track Groups',
                    scheme: 'enrollment_track',
                    groups: [
                      {
                        id: 2,
                        name: 'Verified Certificate',
                        selected: false,
                        deleted: false,
                      },
                      {
                        id: 1,
                        name: 'Audit',
                        selected: false,
                        deleted: false,
                      },
                    ],
                  },
                ],
                show_correctness: 'always',
                discussion_enabled: true,
                ancestor_has_staff_lock: false,
                user_partition_info: {
                  selectable_partitions: [
                    {
                      id: 50,
                      name: 'Enrollment Track Groups',
                      scheme: 'enrollment_track',
                      groups: [
                        {
                          id: 2,
                          name: 'Verified Certificate',
                          selected: false,
                          deleted: false,
                        },
                        {
                          id: 1,
                          name: 'Audit',
                          selected: false,
                          deleted: false,
                        },
                      ],
                    },
                  ],
                  selected_partition_index: -1,
                  selected_groups_label: '',
                },
                enable_copy_paste_units: false,
              },
              {
                id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@4f6c1b4e316a419ab5b6bf30e6c708e9',
                display_name: 'Working with Videos',
                category: 'vertical',
                has_children: true,
                edited_on: 'Dec 28, 2023 at 10:00 UTC',
                published: true,
                published_on: 'Dec 28, 2023 at 10:00 UTC',
                studio_url: '/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@4f6c1b4e316a419ab5b6bf30e6c708e9',
                released_to_students: true,
                release_date: 'Feb 05, 2013 at 05:00 UTC',
                visibility_state: 'live',
                has_explicit_staff_lock: false,
                start: '2013-02-05T05:00:00Z',
                graded: false,
                due_date: '',
                due: null,
                relative_weeks_due: null,
                format: null,
                course_graders: [
                  'Homework',
                  'Exam',
                ],
                has_changes: false,
                actions: {
                  deletable: true,
                  draggable: true,
                  childAddable: true,
                  duplicable: true,
                },
                explanatory_message: null,
                group_access: {},
                user_partitions: [
                  {
                    id: 50,
                    name: 'Enrollment Track Groups',
                    scheme: 'enrollment_track',
                    groups: [
                      {
                        id: 2,
                        name: 'Verified Certificate',
                        selected: false,
                        deleted: false,
                      },
                      {
                        id: 1,
                        name: 'Audit',
                        selected: false,
                        deleted: false,
                      },
                    ],
                  },
                ],
                show_correctness: 'always',
                discussion_enabled: true,
                ancestor_has_staff_lock: false,
                user_partition_info: {
                  selectable_partitions: [
                    {
                      id: 50,
                      name: 'Enrollment Track Groups',
                      scheme: 'enrollment_track',
                      groups: [
                        {
                          id: 2,
                          name: 'Verified Certificate',
                          selected: false,
                          deleted: false,
                        },
                        {
                          id: 1,
                          name: 'Audit',
                          selected: false,
                          deleted: false,
                        },
                      ],
                    },
                  ],
                  selected_partition_index: -1,
                  selected_groups_label: '',
                },
                enable_copy_paste_units: false,
              },
              {
                id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@3dc16db8d14842e38324e95d4030b8a0',
                display_name: 'Videos on edX',
                category: 'vertical',
                has_children: true,
                edited_on: 'Dec 28, 2023 at 10:00 UTC',
                published: true,
                published_on: 'Dec 28, 2023 at 10:00 UTC',
                studio_url: '/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@3dc16db8d14842e38324e95d4030b8a0',
                released_to_students: true,
                release_date: 'Feb 05, 2013 at 05:00 UTC',
                visibility_state: 'live',
                has_explicit_staff_lock: false,
                start: '2013-02-05T05:00:00Z',
                graded: false,
                due_date: '',
                due: null,
                relative_weeks_due: null,
                format: null,
                course_graders: [
                  'Homework',
                  'Exam',
                ],
                has_changes: false,
                actions: {
                  deletable: true,
                  draggable: true,
                  childAddable: true,
                  duplicable: true,
                },
                explanatory_message: null,
                group_access: {},
                user_partitions: [
                  {
                    id: 50,
                    name: 'Enrollment Track Groups',
                    scheme: 'enrollment_track',
                    groups: [
                      {
                        id: 2,
                        name: 'Verified Certificate',
                        selected: false,
                        deleted: false,
                      },
                      {
                        id: 1,
                        name: 'Audit',
                        selected: false,
                        deleted: false,
                      },
                    ],
                  },
                ],
                show_correctness: 'always',
                discussion_enabled: true,
                ancestor_has_staff_lock: false,
                user_partition_info: {
                  selectable_partitions: [
                    {
                      id: 50,
                      name: 'Enrollment Track Groups',
                      scheme: 'enrollment_track',
                      groups: [
                        {
                          id: 2,
                          name: 'Verified Certificate',
                          selected: false,
                          deleted: false,
                        },
                        {
                          id: 1,
                          name: 'Audit',
                          selected: false,
                          deleted: false,
                        },
                      ],
                    },
                  ],
                  selected_partition_index: -1,
                  selected_groups_label: '',
                },
                enable_copy_paste_units: false,
              },
              {
                id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@4a1bba2a403f40bca5ec245e945b0d76',
                display_name: 'Video Demonstrations',
                category: 'vertical',
                has_children: true,
                edited_on: 'Dec 28, 2023 at 10:00 UTC',
                published: true,
                published_on: 'Dec 28, 2023 at 10:00 UTC',
                studio_url: '/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@4a1bba2a403f40bca5ec245e945b0d76',
                released_to_students: true,
                release_date: 'Feb 05, 2013 at 05:00 UTC',
                visibility_state: 'live',
                has_explicit_staff_lock: false,
                start: '2013-02-05T05:00:00Z',
                graded: false,
                due_date: '',
                due: null,
                relative_weeks_due: null,
                format: null,
                course_graders: [
                  'Homework',
                  'Exam',
                ],
                has_changes: false,
                actions: {
                  deletable: true,
                  draggable: true,
                  childAddable: true,
                  duplicable: true,
                },
                explanatory_message: null,
                group_access: {},
                user_partitions: [
                  {
                    id: 50,
                    name: 'Enrollment Track Groups',
                    scheme: 'enrollment_track',
                    groups: [
                      {
                        id: 2,
                        name: 'Verified Certificate',
                        selected: false,
                        deleted: false,
                      },
                      {
                        id: 1,
                        name: 'Audit',
                        selected: false,
                        deleted: false,
                      },
                    ],
                  },
                ],
                show_correctness: 'always',
                discussion_enabled: true,
                ancestor_has_staff_lock: false,
                user_partition_info: {
                  selectable_partitions: [
                    {
                      id: 50,
                      name: 'Enrollment Track Groups',
                      scheme: 'enrollment_track',
                      groups: [
                        {
                          id: 2,
                          name: 'Verified Certificate',
                          selected: false,
                          deleted: false,
                        },
                        {
                          id: 1,
                          name: 'Audit',
                          selected: false,
                          deleted: false,
                        },
                      ],
                    },
                  ],
                  selected_partition_index: -1,
                  selected_groups_label: '',
                },
                enable_copy_paste_units: false,
              },
              {
                id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@256f17a44983429fb1a60802203ee4e0',
                display_name: 'Video Presentation Styles',
                category: 'vertical',
                has_children: true,
                edited_on: 'Dec 28, 2023 at 10:00 UTC',
                published: true,
                published_on: 'Dec 28, 2023 at 10:00 UTC',
                studio_url: '/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@256f17a44983429fb1a60802203ee4e0',
                released_to_students: true,
                release_date: 'Feb 05, 2013 at 05:00 UTC',
                visibility_state: 'live',
                has_explicit_staff_lock: false,
                start: '2013-02-05T05:00:00Z',
                graded: false,
                due_date: '',
                due: null,
                relative_weeks_due: null,
                format: null,
                course_graders: [
                  'Homework',
                  'Exam',
                ],
                has_changes: false,
                actions: {
                  deletable: true,
                  draggable: true,
                  childAddable: true,
                  duplicable: true,
                },
                explanatory_message: null,
                group_access: {},
                user_partitions: [
                  {
                    id: 50,
                    name: 'Enrollment Track Groups',
                    scheme: 'enrollment_track',
                    groups: [
                      {
                        id: 2,
                        name: 'Verified Certificate',
                        selected: false,
                        deleted: false,
                      },
                      {
                        id: 1,
                        name: 'Audit',
                        selected: false,
                        deleted: false,
                      },
                    ],
                  },
                ],
                show_correctness: 'always',
                discussion_enabled: true,
                ancestor_has_staff_lock: false,
                user_partition_info: {
                  selectable_partitions: [
                    {
                      id: 50,
                      name: 'Enrollment Track Groups',
                      scheme: 'enrollment_track',
                      groups: [
                        {
                          id: 2,
                          name: 'Verified Certificate',
                          selected: false,
                          deleted: false,
                        },
                        {
                          id: 1,
                          name: 'Audit',
                          selected: false,
                          deleted: false,
                        },
                      ],
                    },
                  ],
                  selected_partition_index: -1,
                  selected_groups_label: '',
                },
                enable_copy_paste_units: false,
              },
              {
                id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@e3601c0abee6427d8c17e6d6f8fdddd1',
                display_name: 'Interactive Questions',
                category: 'vertical',
                has_children: true,
                edited_on: 'Dec 28, 2023 at 10:00 UTC',
                published: true,
                published_on: 'Dec 28, 2023 at 10:00 UTC',
                studio_url: '/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@e3601c0abee6427d8c17e6d6f8fdddd1',
                released_to_students: true,
                release_date: 'Feb 05, 2013 at 05:00 UTC',
                visibility_state: 'live',
                has_explicit_staff_lock: false,
                start: '2013-02-05T05:00:00Z',
                graded: false,
                due_date: '',
                due: null,
                relative_weeks_due: null,
                format: null,
                course_graders: [
                  'Homework',
                  'Exam',
                ],
                has_changes: false,
                actions: {
                  deletable: true,
                  draggable: true,
                  childAddable: true,
                  duplicable: true,
                },
                explanatory_message: null,
                group_access: {},
                user_partitions: [
                  {
                    id: 50,
                    name: 'Enrollment Track Groups',
                    scheme: 'enrollment_track',
                    groups: [
                      {
                        id: 2,
                        name: 'Verified Certificate',
                        selected: false,
                        deleted: false,
                      },
                      {
                        id: 1,
                        name: 'Audit',
                        selected: false,
                        deleted: false,
                      },
                    ],
                  },
                ],
                show_correctness: 'always',
                discussion_enabled: true,
                ancestor_has_staff_lock: false,
                user_partition_info: {
                  selectable_partitions: [
                    {
                      id: 50,
                      name: 'Enrollment Track Groups',
                      scheme: 'enrollment_track',
                      groups: [
                        {
                          id: 2,
                          name: 'Verified Certificate',
                          selected: false,
                          deleted: false,
                        },
                        {
                          id: 1,
                          name: 'Audit',
                          selected: false,
                          deleted: false,
                        },
                      ],
                    },
                  ],
                  selected_partition_index: -1,
                  selected_groups_label: '',
                },
                enable_copy_paste_units: false,
              },
              {
                id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@a79d59cd72034188a71d388f4954a606',
                display_name: 'Exciting Labs and Tools',
                category: 'vertical',
                has_children: true,
                edited_on: 'Dec 28, 2023 at 10:00 UTC',
                published: true,
                published_on: 'Dec 28, 2023 at 10:00 UTC',
                studio_url: '/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@a79d59cd72034188a71d388f4954a606',
                released_to_students: true,
                release_date: 'Feb 05, 2013 at 05:00 UTC',
                visibility_state: 'live',
                has_explicit_staff_lock: false,
                start: '2013-02-05T05:00:00Z',
                graded: false,
                due_date: '',
                due: null,
                relative_weeks_due: null,
                format: null,
                course_graders: [
                  'Homework',
                  'Exam',
                ],
                has_changes: false,
                actions: {
                  deletable: true,
                  draggable: true,
                  childAddable: true,
                  duplicable: true,
                },
                explanatory_message: null,
                group_access: {},
                user_partitions: [
                  {
                    id: 50,
                    name: 'Enrollment Track Groups',
                    scheme: 'enrollment_track',
                    groups: [
                      {
                        id: 2,
                        name: 'Verified Certificate',
                        selected: false,
                        deleted: false,
                      },
                      {
                        id: 1,
                        name: 'Audit',
                        selected: false,
                        deleted: false,
                      },
                    ],
                  },
                ],
                show_correctness: 'always',
                discussion_enabled: true,
                ancestor_has_staff_lock: false,
                user_partition_info: {
                  selectable_partitions: [
                    {
                      id: 50,
                      name: 'Enrollment Track Groups',
                      scheme: 'enrollment_track',
                      groups: [
                        {
                          id: 2,
                          name: 'Verified Certificate',
                          selected: false,
                          deleted: false,
                        },
                        {
                          id: 1,
                          name: 'Audit',
                          selected: false,
                          deleted: false,
                        },
                      ],
                    },
                  ],
                  selected_partition_index: -1,
                  selected_groups_label: '',
                },
                enable_copy_paste_units: false,
              },
              {
                id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@134df56c516a4a0dbb24dd5facef746e',
                display_name: 'Reading Assignments',
                category: 'vertical',
                has_children: true,
                edited_on: 'Dec 28, 2023 at 10:00 UTC',
                published: true,
                published_on: 'Dec 28, 2023 at 10:00 UTC',
                studio_url: '/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@134df56c516a4a0dbb24dd5facef746e',
                released_to_students: true,
                release_date: 'Feb 05, 2013 at 05:00 UTC',
                visibility_state: 'live',
                has_explicit_staff_lock: false,
                start: '2013-02-05T05:00:00Z',
                graded: false,
                due_date: '',
                due: null,
                relative_weeks_due: null,
                format: null,
                course_graders: [
                  'Homework',
                  'Exam',
                ],
                has_changes: false,
                actions: {
                  deletable: true,
                  draggable: true,
                  childAddable: true,
                  duplicable: true,
                },
                explanatory_message: null,
                group_access: {},
                user_partitions: [
                  {
                    id: 50,
                    name: 'Enrollment Track Groups',
                    scheme: 'enrollment_track',
                    groups: [
                      {
                        id: 2,
                        name: 'Verified Certificate',
                        selected: false,
                        deleted: false,
                      },
                      {
                        id: 1,
                        name: 'Audit',
                        selected: false,
                        deleted: false,
                      },
                    ],
                  },
                ],
                show_correctness: 'always',
                discussion_enabled: true,
                ancestor_has_staff_lock: false,
                user_partition_info: {
                  selectable_partitions: [
                    {
                      id: 50,
                      name: 'Enrollment Track Groups',
                      scheme: 'enrollment_track',
                      groups: [
                        {
                          id: 2,
                          name: 'Verified Certificate',
                          selected: false,
                          deleted: false,
                        },
                        {
                          id: 1,
                          name: 'Audit',
                          selected: false,
                          deleted: false,
                        },
                      ],
                    },
                  ],
                  selected_partition_index: -1,
                  selected_groups_label: '',
                },
                enable_copy_paste_units: false,
              },
              {
                id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d91b9e5d8bc64d57a1332d06bf2f2193',
                display_name: 'When Are Your Exams? ',
                category: 'vertical',
                has_children: true,
                edited_on: 'Dec 28, 2023 at 10:00 UTC',
                published: true,
                published_on: 'Dec 28, 2023 at 10:00 UTC',
                studio_url: '/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@d91b9e5d8bc64d57a1332d06bf2f2193',
                released_to_students: true,
                release_date: 'Feb 05, 2013 at 05:00 UTC',
                visibility_state: 'live',
                has_explicit_staff_lock: false,
                start: '2013-02-05T05:00:00Z',
                graded: false,
                due_date: '',
                due: null,
                relative_weeks_due: null,
                format: null,
                course_graders: [
                  'Homework',
                  'Exam',
                ],
                has_changes: false,
                actions: {
                  deletable: true,
                  draggable: true,
                  childAddable: true,
                  duplicable: true,
                },
                explanatory_message: null,
                group_access: {},
                user_partitions: [
                  {
                    id: 50,
                    name: 'Enrollment Track Groups',
                    scheme: 'enrollment_track',
                    groups: [
                      {
                        id: 2,
                        name: 'Verified Certificate',
                        selected: false,
                        deleted: false,
                      },
                      {
                        id: 1,
                        name: 'Audit',
                        selected: false,
                        deleted: false,
                      },
                    ],
                  },
                ],
                show_correctness: 'always',
                discussion_enabled: true,
                ancestor_has_staff_lock: false,
                user_partition_info: {
                  selectable_partitions: [
                    {
                      id: 50,
                      name: 'Enrollment Track Groups',
                      scheme: 'enrollment_track',
                      groups: [
                        {
                          id: 2,
                          name: 'Verified Certificate',
                          selected: false,
                          deleted: false,
                        },
                        {
                          id: 1,
                          name: 'Audit',
                          selected: false,
                          deleted: false,
                        },
                      ],
                    },
                  ],
                  selected_partition_index: -1,
                  selected_groups_label: '',
                },
                enable_copy_paste_units: false,
              },
            ],
          },
          ancestor_has_staff_lock: false,
          user_partition_info: {
            selectable_partitions: [
              {
                id: 50,
                name: 'Enrollment Track Groups',
                scheme: 'enrollment_track',
                groups: [
                  {
                    id: 2,
                    name: 'Verified Certificate',
                    selected: false,
                    deleted: false,
                  },
                  {
                    id: 1,
                    name: 'Audit',
                    selected: false,
                    deleted: false,
                  },
                ],
              },
            ],
            selected_partition_index: -1,
            selected_groups_label: '',
          },
        },
        {
          id: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@interactive_demonstrations',
          display_name: 'Example Week 1: Getting Started',
          category: 'chapter',
          has_children: true,
          edited_on: 'Jan 04, 2024 at 10:32 UTC',
          published: true,
          published_on: 'Dec 28, 2023 at 10:00 UTC',
          studio_url: '/course/course-v1:edX+DemoX+Demo_Course?show=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40chapter%2Bblock%40interactive_demonstrations',
          released_to_students: true,
          release_date: 'Feb 05, 2013 at 05:00 UTC',
          visibility_state: 'live',
          has_explicit_staff_lock: false,
          start: '2013-02-05T05:00:00Z',
          graded: false,
          due_date: '',
          due: null,
          relative_weeks_due: null,
          format: null,
          course_graders: [
            'Homework',
            'Exam',
          ],
          has_changes: null,
          actions: {
            deletable: true,
            draggable: true,
            childAddable: true,
            duplicable: true,
          },
          explanatory_message: null,
          group_access: {},
          user_partitions: [
            {
              id: 50,
              name: 'Enrollment Track Groups',
              scheme: 'enrollment_track',
              groups: [
                {
                  id: 2,
                  name: 'Verified Certificate',
                  selected: false,
                  deleted: false,
                },
                {
                  id: 1,
                  name: 'Audit',
                  selected: false,
                  deleted: false,
                },
              ],
            },
          ],
          show_correctness: 'always',
          highlights: [],
          highlights_enabled: true,
          highlights_preview_only: false,
          highlights_doc_url: 'http://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/developing_course/course_sections.html#set-section-highlights-for-weekly-course-highlight-messages',
          ancestor_has_staff_lock: false,
          user_partition_info: {
            selectable_partitions: [
              {
                id: 50,
                name: 'Enrollment Track Groups',
                scheme: 'enrollment_track',
                groups: [
                  {
                    id: 2,
                    name: 'Verified Certificate',
                    selected: false,
                    deleted: false,
                  },
                  {
                    id: 1,
                    name: 'Audit',
                    selected: false,
                    deleted: false,
                  },
                ],
              },
            ],
            selected_partition_index: -1,
            selected_groups_label: '',
          },
        },
        {
          id: 'block-v1:edX+DemoX+Demo_Course+type@course+block@course',
          display_name: 'Demonstration Course',
          category: 'course',
          has_children: true,
          unit_level_discussions: false,
          edited_on: 'Jan 08, 2024 at 16:39 UTC',
          published: true,
          published_on: 'Jan 08, 2024 at 16:39 UTC',
          studio_url: '/course/course-v1:edX+DemoX+Demo_Course',
          released_to_students: true,
          release_date: 'Feb 05, 2013 at 05:00 UTC',
          visibility_state: null,
          has_explicit_staff_lock: false,
          start: '2013-02-05T05:00:00Z',
          graded: false,
          due_date: '',
          due: null,
          relative_weeks_due: null,
          format: null,
          course_graders: [
            'Homework',
            'Exam',
          ],
          has_changes: null,
          actions: {
            deletable: true,
            draggable: true,
            childAddable: true,
            duplicable: true,
          },
          explanatory_message: null,
          group_access: {},
          user_partitions: [
            {
              id: 50,
              name: 'Enrollment Track Groups',
              scheme: 'enrollment_track',
              groups: [
                {
                  id: 2,
                  name: 'Verified Certificate',
                  selected: false,
                  deleted: false,
                },
                {
                  id: 1,
                  name: 'Audit',
                  selected: false,
                  deleted: false,
                },
              ],
            },
          ],
          show_correctness: 'always',
          highlights_enabled_for_messaging: false,
          highlights_enabled: true,
          highlights_preview_only: false,
          highlights_doc_url: 'http://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/developing_course/course_sections.html#set-section-highlights-for-weekly-course-highlight-messages',
          enable_proctored_exams: false,
          create_zendesk_tickets: true,
          enable_timed_exams: true,
          ancestor_has_staff_lock: false,
          user_partition_info: {
            selectable_partitions: [
              {
                id: 50,
                name: 'Enrollment Track Groups',
                scheme: 'enrollment_track',
                groups: [
                  {
                    id: 2,
                    name: 'Verified Certificate',
                    selected: false,
                    deleted: false,
                  },
                  {
                    id: 1,
                    name: 'Audit',
                    selected: false,
                    deleted: false,
                  },
                ],
              },
            ],
            selected_partition_index: -1,
            selected_groups_label: '',
          },
        },
      ],
    },
    ancestor_has_staff_lock: false,
    user_partition_info: {
      selectable_partitions: [
        {
          id: 50,
          name: 'Enrollment Track Groups',
          scheme: 'enrollment_track',
          groups: [
            {
              id: 2,
              name: 'Verified Certificate',
              selected: false,
              deleted: false,
            },
            {
              id: 1,
              name: 'Audit',
              selected: false,
              deleted: false,
            },
          ],
        },
      ],
      selected_partition_index: -1,
      selected_groups_label: '',
    },
    enable_copy_paste_units: false,
    edited_by: 'edx',
    published_by: null,
    currently_visible_to_students: true,
    has_partition_group_components: false,
    release_date_from: 'Section "Example Week 1: Getting Started"',
    staff_lock_from: null,
  },
  draft_preview_link: '//preview.localhost:18000/courses/course-v1:edX+DemoX+Demo_Course/jump_to/block-v1:edX+DemoX+Demo_Course+type@vertical+block@867dddb6f55d410caaa9c1eb9c6743ec',
  published_preview_link: '//localhost:18000/courses/course-v1:edX+DemoX+Demo_Course/jump_to/block-v1:edX+DemoX+Demo_Course+type@vertical+block@867dddb6f55d410caaa9c1eb9c6743ec',
  show_unit_tags: false,
  user_clipboard: {
    content: null,
    source_usage_key: '',
    source_context_title: '',
    source_edit_url: '',
  },
  is_fullwidth_content: false,
  assets_url: '/assets/course-v1:edX+DemoX+Demo_Course/',
  unit_block_id: '867dddb6f55d410caaa9c1eb9c6743ec',
  subsection_location: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5',
};
