module.exports = {
  id: 'block-v1:edX+DemoX+Demo_Course+type@vertical+block@d91b9e5d8bc64d57a1332d06bf2f2144',
  display_name: 'Getting Started new',
  category: 'vertical',
  has_children: true,
  edited_on: 'Dec 28, 2023 at 10:00 UTC',
  published: true,
  published_on: 'Dec 28, 2023 at 10:00 UTC',
  studio_url: '/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@d91b9e5d8bc64d57a1332d06bf2f2193',
  released_to_students: true,
  release_date: 'Feb 05, 2013 at 05:00 UTC',
  visibility_state: 'live',
  has_explicit_staff_lock: false,
  start: '2013-02-05T05:00:00Z',
  graded: false,
  due_date: '',
  due: null,
  relative_weeks_due: null,
  format: null,
  course_graders: [
    'Homework',
    'Exam',
  ],
  has_changes: false,
  actions: {
    deletable: true,
    draggable: true,
    childAddable: true,
    duplicable: true,
  },
  explanatory_message: null,
  group_access: {},
  user_partitions: [
    {
      id: 50,
      name: 'Enrollment Track Groups',
      scheme: 'enrollment_track',
      groups: [
        {
          id: 2,
          name: 'Verified Certificate',
          selected: false,
          deleted: false,
        },
        {
          id: 1,
          name: 'Audit',
          selected: false,
          deleted: false,
        },
      ],
    },
  ],
  show_correctness: 'always',
  discussion_enabled: true,
  ancestor_has_staff_lock: false,
  user_partition_info: {
    selectable_partitions: [
      {
        id: 50,
        name: 'Enrollment Track Groups',
        scheme: 'enrollment_track',
        groups: [
          {
            id: 2,
            name: 'Verified Certificate',
            selected: false,
            deleted: false,
          },
          {
            id: 1,
            name: 'Audit',
            selected: false,
            deleted: false,
          },
        ],
      },
    ],
    selected_partition_index: -1,
    selected_groups_label: '',
  },
  enable_copy_paste_units: false,
  xblock_type: 'other',
};
