module.exports = {
  activeTab: 'courses',
  allowCourseReruns: true,
  allowedOrganizations: ['edx', 'org'],
  archivedCourses: [
    {
      courseKey: 'course-v1:MachineLearning+123+2023',
      displayName: 'Machine Learning',
      lmsLink: '//localhost:18000/courses/course-v1:MachineLearning+123+2023/jump_to/block-v1:MachineLearning+123+2023+type@course+block@course',
      number: '123',
      org: 'LSE',
      rerunLink: '/course_rerun/course-v1:MachineLearning+123+2023',
      run: '2023',
      url: '/course/course-v1:MachineLearning+123+2023',
      cmsLink: '//localhost:18010/courses/course-v1:MachineLearning+123+2023',
    },
    {
      courseKey: 'course-v1:Design+123+e.g.2025',
      displayName: 'Design',
      lmsLink: '//localhost:18000/courses/course-v1:Design+123+e.g.2025/jump_to/block-v1:Design+123+e.g.2025+type@course+block@course',
      number: '123',
      org: 'University of Cape Town',
      rerunLink: '/course_rerun/course-v1:Design+123+e.g.2025',
      run: 'e.g.2025',
      url: '/course/course-v1:Design+123+e.g.2025',
      cmsLink: '//localhost:18010/courses/course-v1:Design+123+e.g.2025',
    },
  ],
  canCreateOrganizations: true,
  courseCreatorStatus: 'granted',
  courses: [
    {
      courseKey: 'course-v1:HarvardX+123+2023',
      displayName: 'Managing Risk in the Information Age',
      lmsLink: '//localhost:18000/courses/course-v1:HarvardX+123+2023/jump_to/block-v1:HarvardX+123+2023+type@course+block@course',
      number: '123',
      org: 'HarvardX',
      rerunLink: '/course_rerun/course-v1:HarvardX+123+2023',
      run: '2023',
      url: '/course/course-v1:HarvardX+123+2023',
    },
    {
      courseKey: 'org.0/course_0/Run_0',
      displayName: 'Run 0',
      lmsLink: null,
      number: 'course_0',
      org: 'org.0',
      rerunLink: null,
      run: 'Run_0',
      url: '',
    },
  ],
  inProcessCourseActions: [],
  libraries: [
    {
      displayName: 'MBA',
      libraryKey: 'library-v1:MBA+123',
      url: '/library/library-v1:MDA+123',
      org: 'Cambridge',
      number: '123',
      canEdit: true,
    },
  ],
  librariesV1Enabled: true,
  librariesV2Enabled: true,
  optimizationEnabled: false,
  requestCourseCreatorUrl: '/request_course_creator',
  rerunCreatorStatus: true,
  showNewLibraryButton: true,
  showNewLibraryV2Button: true,
  splitStudioHome: false,
  studioName: 'Studio',
  studioShortName: 'Studio',
  studioRequestEmail: 'request@email.com',
  techSupportEmail: 'technical@example.com',
  platformName: 'Your Platform Name Here',
  userIsActive: true,
  allowToCreateNewOrg: false,
};
