module.exports = {
  next: null,
  previous: null,
  count: 4,
  numPages: 1,
  currentPage: 1,
  start: 0,
  canAddTaxonomy: true,
  results: [
    {
      id: -2,
      name: 'Content Authors',
      description: 'Allows tags for any user ID created on the instance.',
      taxonomyType: 'tags',
      enabled: true,
      allowMultiple: false,
      allowFreeText: false,
      readOnly: true,
      visibleToAuthors: false,
      canChangeTaxonomy: false,
      canDeleteTaxonomy: false,
      canTagObject: true,
    },
    {
      id: -1,
      name: 'Languages',
      description: 'lang lang lang lang lang lang lang lang',
      taxonomyType: 'tags',
      enabled: true,
      allowMultiple: false,
      allowFreeText: false,
      readOnly: true,
      visibleToAuthors: true,
      canChangeTaxonomy: false,
      canDeleteTaxonomy: false,
      canTagObject: true,
    },
    {
      id: 1,
      name: 'Taxonomy',
      description: 'This is a Description',
      taxonomyType: 'competency',
      enabled: true,
      allowMultiple: false,
      allowFreeText: false,
      readOnly: false,
      visibleToAuthors: true,
      canChangeTaxonomy: true,
      canDeleteTaxonomy: true,
      canTagObject: true,
    },
    {
      id: 2,
      name: 'Taxonomy long long long long long long long long long long long long long long long long long long long',
      description: 'This is a Description long lon',
      taxonomyType: 'tags',
      enabled: true,
      allowMultiple: false,
      allowFreeText: false,
      readOnly: false,
      visibleToAuthors: true,
      canChangeTaxonomy: true,
      canDeleteTaxonomy: true,
      canTagObject: true,
    },
  ],
};
