module.exports = {
  id: 'block-v1:SampleTaxonomyOrg1+STC1+2023_1+type@vertical+block@7f47fe2dbcaf47c5a071671c741fe1ab',
  displayName: 'Unit 1.1.2',
  category: 'vertical',
  hasChildren: true,
  editedOn: 'Nov 12, 2023 at 09:53 UTC',
  published: false,
  publishedOn: null,
  studioUrl: '/container/block-v1:SampleTaxonomyOrg1+STC1+2023_1+type@vertical+block@7f47fe2dbcaf47c5a071671c741fe1ab',
  releasedToStudents: false,
  releaseDate: null,
  visibilityState: 'needs_attention',
  hasExplicitStaffLock: false,
  start: '2030-01-01T00:00:00Z',
  graded: false,
  dueDate: '',
  due: null,
  relativeWeeksDue: null,
  format: null,
  courseGraders: [
    'Homework',
    'Lab',
    'Midterm Exam',
    'Final Exam',
  ],
  hasChanges: true,
  actions: {
    deletable: true,
    draggable: true,
    childAddable: true,
    duplicable: true,
  },
  explanatoryMessage: null,
  groupAccess: {},
  userPartitions: [
    {
      id: 50,
      name: 'Enrollment Track Groups',
      scheme: 'enrollment_track',
      groups: [
        {
          id: 1,
          name: 'Audit',
          selected: false,
          deleted: false,
        },
      ],
    },
  ],
  showCorrectness: 'always',
  discussionEnabled: true,
  ancestorHasStaffLock: false,
  taxonomyTagsWidgetUrl: 'http://localhost:2001/tagging/components/widget/',
  staffOnlyMessage: false,
  enableCopyPasteUnits: true,
  useTaggingTaxonomyListPage: true,
  hasPartitionGroupComponents: false,
  userPartitionInfo: {
    selectablePartitions: [],
    selectedPartitionIndex: -1,
    selectedGroupsLabel: '',
  },
};
