module.exports = {
  next: null,
  previous: null,
  count: 4,
  numPages: 1,
  currentPage: 1,
  start: 0,
  results: [
    {
      value: 'tag 1',
      externalId: null,
      childCount: 16,
      depth: 0,
      parentValue: null,
      id: 635951,
      subTagsUrl: 'http://localhost:18010/api/content_tagging/v1/taxonomies/4/tags/?parent_tag=tag%201',
    },
    {
      value: 'tag 2',
      externalId: null,
      childCount: 16,
      depth: 0,
      parentValue: null,
      id: 636992,
      subTagsUrl: 'http://localhost:18010/api/content_tagging/v1/taxonomies/4/tags/?parent_tag=tag%202',
    },
    {
      value: 'tag 3',
      externalId: null,
      childCount: 16,
      depth: 0,
      parentValue: null,
      id: 638033,
      subTagsUrl: 'http://localhost:18010/api/content_tagging/v1/taxonomies/4/tags/?parent_tag=tag%203',
    },
    {
      value: 'tag 4',
      externalId: null,
      childCount: 16,
      depth: 0,
      parentValue: null,
      id: 639074,
      subTagsUrl: 'http://localhost:18010/api/content_tagging/v1/taxonomies/4/tags/?parent_tag=tag%204',
    },
  ],
};
