module.exports = {
  next: null,
  previous: null,
  count: 2,
  num_pages: 2,
  current_page: 1,
  start: 0,
  results: [
    {
      id: 'lib:SampleTaxonomyOrg1:AL1',
      type: 'complex',
      org: 'SampleTaxonomyOrg1',
      slug: 'AL1',
      title: 'Another Library 2',
      description: '',
      num_blocks: 0,
      version: 0,
      last_published: null,
      allow_lti: false,
      allow_public_learning: false,
      allow_public_read: false,
      has_unpublished_changes: false,
      has_unpublished_deletes: false,
      license: '',
    },
    {
      id: 'lib:SampleTaxonomyOrg1:TL1',
      type: 'complex',
      org: 'SampleTaxonomyOrg1',
      slug: 'TL1',
      title: 'Test Library 1',
      description: '',
      num_blocks: 0,
      version: 0,
      last_published: null,
      allow_lti: false,
      allow_public_learning: false,
      allow_public_read: false,
      has_unpublished_changes: false,
      has_unpublished_deletes: false,
      license: '',
    },
  ],
};
