module.exports = {
  id: 'block-v1:edX+DemoX+Demo_Course+type@sequential+block@b713bc2830f34f6f87554028c3068729',
  display_name: 'Subsection',
  category: 'sequential',
  has_children: true,
  edited_on: 'Dec 05, 2023 at 10:35 UTC',
  published: true,
  published_on: 'Dec 05, 2023 at 10:35 UTC',
  studio_url: '/course/course-v1:edX+DemoX+Demo_Course?show=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40sequential%2Bblock%40b713bc2830f34f6f87554028c3068729',
  released_to_students: true,
  release_date: 'Feb 05, 2013 at 05:00 UTC',
  visibility_state: 'live',
  has_explicit_staff_lock: false,
  start: '2013-02-05T05:00:00Z',
  graded: false,
  due_date: '',
  due: null,
  relative_weeks_due: null,
  format: null,
  course_graders: [
    'Homework',
    'Exam',
  ],
  has_changes: false,
  actions: {
    deletable: true,
    draggable: true,
    childAddable: true,
    duplicable: true,
  },
  explanatory_message: null,
  group_access: {},
  user_partitions: [
    {
      id: 50,
      name: 'Enrollment Track Groups',
      scheme: 'enrollment_track',
      groups: [
        {
          id: 2,
          name: 'Verified Certificate',
          selected: false,
          deleted: false,
        },
        {
          id: 1,
          name: 'Audit',
          selected: false,
          deleted: false,
        },
      ],
    },
  ],
  show_correctness: 'always',
  hide_after_due: false,
  is_proctored_exam: false,
  was_exam_ever_linked_with_external: false,
  online_proctoring_rules: '',
  is_practice_exam: false,
  is_onboarding_exam: false,
  is_time_limited: false,
  exam_review_rules: '',
  default_time_limit_minutes: null,
  proctoring_exam_configuration_link: null,
  supports_onboarding: false,
  show_review_rules: true,
  child_info: {
    category: 'vertical',
    display_name: 'Unit',
    children: [],
  },
  ancestor_has_staff_lock: false,
  staff_only_message: false,
  enable_copy_paste_units: false,
  has_partition_group_components: false,
  user_partition_info: {
    selectable_partitions: [
      {
        id: 50,
        name: 'Enrollment Track Groups',
        scheme: 'enrollment_track',
        groups: [
          {
            id: 2,
            name: 'Verified Certificate',
            selected: false,
            deleted: false,
          },
          {
            id: 1,
            name: 'Audit',
            selected: false,
            deleted: false,
          },
        ],
      },
    ],
    selected_partition_index: -1,
    selected_groups_label: '',
  },
};
