module.exports = {
  id: 'block-v1:edX+DemoX+Demo_Course+type@chapter+block@d0e78d363a424da6be5c22704c34f7a7',
  display_name: 'Section',
  category: 'chapter',
  has_children: true,
  edited_on: 'Nov 22, 2023 at 07:45 UTC',
  published: true,
  published_on: 'Nov 22, 2023 at 07:45 UTC',
  studio_url: '/course/course-v1:edX+DemoX+Demo_Course?show=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40chapter%2Bblock%40d0e78d363a424da6be5c22704c34f7a7',
  released_to_students: true,
  release_date: 'Feb 05, 2013 at 05:00 UTC',
  visibility_state: 'live',
  has_explicit_staff_lock: false,
  start: '2013-02-05T05:00:00Z',
  graded: false,
  due_date: '',
  due: null,
  relative_weeks_due: null,
  format: null,
  course_graders: [
    'Homework',
    'Exam',
  ],
  has_changes: false,
  actions: {
    deletable: true,
    draggable: true,
    childAddable: true,
    duplicable: true,
  },
  explanatory_message: null,
  group_access: {},
  user_partitions: [
    {
      id: 50,
      name: 'Enrollment Track Groups',
      scheme: 'enrollment_track',
      groups: [
        {
          id: 2,
          name: 'Verified Certificate',
          selected: false,
          deleted: false,
        },
        {
          id: 1,
          name: 'Audit',
          selected: false,
          deleted: false,
        },
      ],
    },
  ],
  show_correctness: 'always',
  highlights: [],
  highlights_enabled: true,
  highlights_preview_only: false,
  highlights_doc_url: 'http://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/developing_course/course_sections.html#set-section-highlights-for-weekly-course-highlight-messages',
  child_info: {
    category: 'sequential',
    display_name: 'Subsection',
    children: [],
  },
  ancestor_has_staff_lock: false,
  staff_only_message: false,
  enable_copy_paste_units: false,
  has_partition_group_components: false,
  user_partition_info: {
    selectable_partitions: [
      {
        id: 50,
        name: 'Enrollment Track Groups',
        scheme: 'enrollment_track',
        groups: [
          {
            id: 2,
            name: 'Verified Certificate',
            selected: false,
            deleted: false,
          },
          {
            id: 1,
            name: 'Audit',
            selected: false,
            deleted: false,
          },
        ],
      },
    ],
    selected_partition_index: -1,
    selected_groups_label: '',
  },
};
