name: validate
on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - '**'
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
    - run: make validate.ci
    - name: Archive code coverage results
      uses: actions/upload-artifact@v7
      with:
        name: code-coverage-report
        path: coverage/*.*
